### ISSUE TITLE
Link not working in player

### ISSUE THREAD

**Issue by moaid500** [namhong1412/Google-Drive-Stream-Proxy-2020#10]
Hello, 

I tried the script and it is working only when paste the link on the browser : 
[https://pro.segavid.com/drive.php?id=ef10f175bdf79da9702d452fbd1b63ebb6648072e7404a987bf1db9ca04b572d&stream=1080p](url)

But when use the on any player on websites such :
[https://pro.segavid.com/stream/?link=https://pro.segavid.com/drive.php?id=ef10f175bdf79da9702d452fbd1b63ebb6648072e7404a987bf1db9ca04b572d&stream=1080p](url)
not working 

But our stream link not working. Any Seggestion ? 

Thanks

**Comment by namhong1412** [comment]
Currently, I did stop develop this script
